#! /bin/sh
usage () {
	echo "Usage: cherrygit [--server | -s]"
}
if [ $# = 0 ]
	then python main.py; exit 0
else if [ $# = 1 ] 
	then
		if [ $1 = '--server' -o $1 = '-s' ]
			then python main.py server; exit 0
		fi
	fi
fi
usage
exit 0